// Core types for Sentinel IRM Platform

export interface Asset {
  id: string;
  name: string;
  type: 'APPLICATION' | 'DATABASE' | 'SERVER' | 'NETWORK' | 'CLOUD' | 'CONTAINER' | 'MICROSERVICE' | 'INFRASTRUCTURE';
  owner: string;
  ownerId?: string;
  classification: 'PUBLIC' | 'INTERNAL' | 'CONFIDENTIAL' | 'RESTRICTED';
  confidentiality: number;
  integrity: number;
  availability: number;
  sensitivityScore: number;
  status: 'Active' | 'Inactive' | 'Deprecated';
  environment: 'Production' | 'Staging' | 'Development';
  lastScanned: string;
  threatCount: number;
  findingsCount: number;
  technologyStack?: string[];
  createdAt?: string;
  updatedAt?: string;
}

export interface Threat {
  id: string;
  title: string;
  assetId: string;
  assetName: string;
  strideCategory?: 'SPOOFING' | 'TAMPERING' | 'REPUDIATION' | 'INFO_DISCLOSURE' | 'DOS' | 'ELEVATION';
  mitreAttackId?: string;
  category: 'External' | 'Internal' | 'Physical' | 'Technical';
  likelihood: number;
  impact: number;
  riskScore: number;
  status: 'IDENTIFIED' | 'ASSESSED' | 'VERIFIED' | 'EVALUATED' | 'PLANNING' | 'MITIGATED' | 'ACCEPTED' | 'MONITORING';
  mitigationPlan?: string;
  owner: string;
  ownerId?: string;
  autoGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Finding {
  id: string;
  title: string;
  assetId: string;
  assetName: string;
  threatId?: string;
  vulnerabilityType?: string;
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO';
  source: 'SonarQube' | 'OWASP ZAP' | 'Snyk' | 'Terraform' | 'Manual';
  status: 'OPEN' | 'IN_PROGRESS' | 'REMEDIATED' | 'FALSE_POSITIVE' | 'ACCEPTED';
  cveId?: string;
  cvssScore?: number;
  description: string;
  remediation: string;
  location?: string;
  scannerSources?: string[];
  discoveredAt: string;
  dueDate: string;
  remediatedAt?: string;
}

export interface Policy {
  id: string;
  name: string;
  description: string;
  framework: string;
  severity: 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  regoSnippet?: string;
  status: 'Active' | 'Draft' | 'Archived';
  active: boolean;
  version: number;
  controlsMapped: number;
  lastEvaluated?: string;
  passRate: number;
  violations: number;
}

export interface ComplianceFramework {
  id: string;
  name: string;
  shortName: string;
  totalControls: number;
  mappedControls: number;
  coverage: number;
  status: 'Compliant' | 'Partial' | 'Non-Compliant';
}

export interface Control {
  id: string;
  framework: 'NIST_800_53' | 'ISO_27001' | 'PCI_DSS' | 'HIPAA' | 'GDPR';
  controlCode: string;
  description: string;
}

export interface RiskAcceptance {
  id: string;
  threatId: string;
  requestedBy: string;
  approvedBy?: string;
  justification: string;
  acceptancePeriodDays: number;
  expirationDate: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'EXPIRED';
  approvalSignatureName?: string;
  approvalSignatureTimestamp?: string;
}

export interface User {
  id: string;
  email: string;
  fullName: string;
  role: 'Security_Architect' | 'Compliance_Officer' | 'Developer' | 'Executive';
  permissions: string[];
}

export interface ApiResponse<T> {
  data: T;
  message?: string;
  error?: string;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}



